AWSTemplateFormatVersion: 2010-09-09
Description: Transit Gateway {{ transit_gateway_name }}.

Resources:
  TransitGateway:
    Type: AWS::EC2::TransitGateway
    Properties:
      AmazonSideAsn: {{ aws_side_asn }}
      {% if description %}
      AssociationDefaultRouteTableId: {{ association_default_route_table_id }}
      {% endif %}
      AutoAcceptSharedAttachments: {{ auto_accept_shared_attachments }}
      DefaultRouteTableAssociation: {{ default_route_table_association }}
      DefaultRouteTablePropagation: {{ default_route_table_propagation }}
      {% if description %}
      Description: {{ description }}
      {% endif %}
      DnsSupport: {{ dns_support }}
      MulticastSupport: {{ multicast_support }}
      PropagationDefaultRouteTableId: {{ propagation_default_route_tableId }}
      {% if transit_gateway_cidr_blocks %}
      TransitGatewayCidrBlocks:
        {% for cidr in transit_gateway_cidr_blocks %}
        - {{ cidr }}
        {% endfor %}
      {% endif %}
      VpnEcmpSupport: {{ vpn_ecmp_support }}
      Tags:
        - Key: Name
          Value: {{ transit_gateway_name }}
        - Key: Creator
          Value: cp4na
  TransitGatewayRouteTable:
    Type: AWS::EC2::TransitGatewayRouteTable
    Properties:
      Tags:
        - Key: Creator
          Value: cp4na
      TransitGatewayId: !Ref TransitGateway

Outputs:
  TGWID:
    Description: A reference to the created Transit Gateway
    Value: !Ref TransitGateway
  TGWRTID:
    Description: A reference to the created Transit Gateway Route Table
    Value: !Ref TransitGatewayRouteTable

