AWSTemplateFormatVersion: 2010-09-09
Description: Transit Gateway Route Table Attachment and Association for Transit Gateway {{ transit_gateway_id }} and Subnet {{ subnet_id }}.

# this is created only when public_private != 'public' - see resourcedriver createtgwroutetableassociation

Resources:
  TransitGatewayAttachment:
    Type: AWS::EC2::TransitGatewayVpcAttachment
    Properties:
      AddSubnetIds:
        - {{ updated_subnet_id }}
      SubnetIds:
      {%- for line in subnet_ids %}
        - {{ line -}}
      {% endfor %}
      TransitGatewayId: {{ transit_gateway_id }}
      VpcId: {{ vpc_id }}
Outputs:
  {{ vpc_id | replace("-","") + "TGWATTACHID"}}:
    Description: A reference to the created Transit Gateway Attachment
    Value: !Ref TransitGatewayAttachment
